
USE DB_RENIEC
-- QUERY PARA EL STAGING
--Maestro Base Registro
SELECT (ANIO_REGISTRO + MES_REGISTRO) AS FechaRegistro,
TIPO_ACTA as Tipo,
DE_GENERO as Genero,
DEPART_CIUDAD_ESTADO_DOM_SOL,
PROVINCIA_DOM_SOL,
CANT_COPIAS_EMITIDAS
FROM BaseRegistro

--Maestro zona
SELECT DISTINCT
    cod_pais as PaisID,
    TRIM(zona) AS 'zona'
FROM (
    SELECT 
        2 AS cod_pais,
        TRIM(DEPART_CIUDAD_ESTADO_DOM_SOL) AS Zona
    FROM
        BaseRegistro
    WHERE
        DEPART_CIUDAD_ESTADO_DOM_SOL IN (
            'AMAZONAS', 'ANCASH', 'APURIMAC', 'AREQUIPA', 'AYACUCHO', 'CAJAMARCA', 'CALLAO', 'CUSCO', 'HUANCAVELICA', 'HUANUCO', 'ICA', 'JUNIN', 'LA LIBERTAD', 'LAMBAYEQUE', 'LIMA', 'LORETO', 'MADRE DE DIOS', 'MOQUEGUA', 'PASCO', 'PIURA', 'PUNO', 'SAN MARTIN', 'TACNA', 'TUMBES', 'UCAYALI'
        )
    UNION
    SELECT
        1 AS cod_pais,
        TRIM(DEPART_CIUDAD_ESTADO_DOM_SOL) AS zona
    FROM
        BaseRegistro
    WHERE
        DEPART_CIUDAD_ESTADO_DOM_SOL NOT IN (
            'AMAZONAS', 'ANCASH', 'APURIMAC', 'AREQUIPA', 'AYACUCHO', 'CAJAMARCA', 'CALLAO', 'CUSCO', 'HUANCAVELICA', 'HUANUCO', 'ICA', 'JUNIN', 'LA LIBERTAD', 'LAMBAYEQUE', 'LIMA', 'LORETO', 'MADRE DE DIOS', 'MOQUEGUA', 'PASCO', 'PIURA', 'PUNO', 'SAN MARTIN', 'TACNA', 'TUMBES', 'UCAYALI'
        )
) AS QUERY


-- QUERY PARAR DATAWAREHOUSE

--DIMENSIONES

--DimGenero
SELECT DISTINCT 
   CONVERT(NVARCHAR(1), CASE DE_GENERO 
        WHEN 'FEMENINO' THEN 'F'
        ELSE 'M'
    END ) AS GeneroID,
    CONVERT(NVARCHAR(10), DE_GENERO) AS Genero
FROM BaseRegistro;

--DimTipoActa
SELECT DISTINCT SUBSTRING(TIPO_ACTA,1,3) as ActaID, TIPO_ACTA as Tipo FROM BaseRegistro

-- DimFecha
SELECT DISTINCT (ANIO_REGISTRO+MES_REGISTRO) AS FechaID,
ANIO_REGISTRO as Anio ,MES_REGISTRO as Mes FROM BaseRegistro
-- DimPais
SELECT DISTINCT paisID, 
	CASE paisID
		WHEN '2' THEN 'PERÚ'
		ELSE  'OTROS'
	END AS Pais
FROM ETL_Zona

-- DimZona
SELECT TRIM(zona) as Zona, PaisID FROM ETL_Zona

--FACT
SELECT 
	BR.FechaRegistro,
	DT.ActaID AS 'TipoActa', 
	DZ.Zona AS 'Zonas',
	DS.GeneroID AS 'Genero',
	CAST(BR.CANT_COPIAS_EMITIDAS  AS INT ) AS 'Copias'
FROM [DB_RENIEC].[dbo].[ETL_BaseRegistro] BR
LEFT JOIN [DATAWAREHOUSE_RENIEC].[dbo].[DimTipo] DT ON DT.Tipo = BR.Tipo
LEFT JOIN [DATAWAREHOUSE_RENIEC].[dbo].[DimZona] DZ On DZ.Zona = BR.DEPART_CIUDAD_ESTADO_DOM_SOL
LEFT JOIN [DATAWAREHOUSE_RENIEC].[dbo].[DimGenero] DS ON DS.genero = BR.Genero